### ISSUE TITLE
Sync stuck at block 849137

### ISSUE THREAD

**Issue by yuanyangzi** [bitcoin-wallet/bitcoin-wallet#1152] opened 2024-06-23 16:31 UTC
The android bitcoin wallet version is 10.14. It's stuck even if I download a new apk and start a new sync.Always stopped at 849137.

**Comment by 32xxl** [comment] 2024-06-23 22:24
Have you fixed already? 
If no, don't panik, today is sunday. 
I have the same issue. 
Just make copy of private keys, and wait for updates from devs.

**Comment by yuanyangzi** [comment] 2024-06-23 22:42
> Have you fixed already? 
> If no, don't panik, today is sunday. 
> I have the same issue. 
> Just make copy of private keys, and wait for updates from devs. 

Thanks. Not fixed, I saw you have the same problem and my phone is Samsung too. I copied my private key and download desktop version to see if there's the same problem.

**Comment by schildbach** [comment] 2024-06-24 23:55
Duplicate of #1154.

**Closed by schildbach** 2024-06-24 23:55 UTC
