### ISSUE TITLE
F-Droid release is behind

### ISSUE THREAD

**Issue by betsythefc** [bitcoin-wallet/bitcoin-wallet#573] opened 2019-03-06 19:14 UTC
The newest Release is 7.0, but only 6.35 is available from 3 months ago on F-Droid.

**Comment by schildbach** [comment] 2019-03-07 14:11
The speed of updates on F-Droid is not in our hands. So I'm closing this.

**Closed by schildbach** 2019-03-07 14:11 UTC

**Comment by schildbach** [comment] 2020-11-22 20:10
Just for the record: This issue is tracked at Duplicate of https://gitlab.com/fdroid/fdroiddata/-/issues/1884
