### ISSUE TITLE
BIP 72 Support

### ISSUE THREAD

**Issue by haight6716** [bitcoin-wallet/bitcoin-wallet#94] opened 2014-06-13 19:23 UTC
bitcoin-wallet does not properly support BIP 72.

Quoting the BIP:
https://github.com/bitcoin/bips/blob/master/bip-0072.mediawiki

> If the "r" parameter is provided and backwards compatibility is not required, then the bitcoin address portion of the URI may be omitted (the URI will be of the form: bitcoin:?r=... ).
> 
> When Bitcoin wallet software that supports this BIP receives a bitcoin: URI with a request parameter, it should ignore the bitcoin address/amount/label/message in the URI and instead fetch a PaymentRequest message and then follow the payment protocol, as described in BIP 70.

bitcoin-wallet reports "Fetching signature failed: wrong signature!" instead of generating the requested payment when presented with a valid BIP 72 link.

Here's the test case:
https://www.syndicoin.co/demo.html

There are three test payment requests on that page.  None of them load correctly using the BIP 72 link, but they do load correctly when downloaded and opened directly.

Thanks for your efforts!

Edit to add:

This bug is perhaps illustrated best by the text I've written explaining the workaround for users of bitcoin-wallet:

> ... you must use the "download" link and then open the payment request from your downloaded files.
> To scan a QR code into bitcoin wallet is also cumbersome.  You must first scan the download QR code using a scanner **outside** bitcoin-wallet.  Then, once the file is downloaded, tap it to launch bitcoin-wallet and pay it.

**Comment by schildbach** [comment] 2015-05-23 14:28
FWIW, I recently documented the restriction of BIP-72 support via 7954464bc13d44cd9381d70c97115f9a4aee3c31#diff-0161f2acee7aeafff9a09f11f2ebde3f.

**Comment by schildbach** [comment] 2019-10-29 20:50
I'm closing this as works as intended.

**Closed by schildbach** 2019-10-29 20:50 UTC
