### ISSUE TITLE
Use github releases for newer versions & publish .apk file in them & currently latest github release is old 5.45 from 2018

### ISSUE THREAD

**Issue by emanuelb** [bitcoin-wallet/bitcoin-wallet#712] opened 2021-05-15 01:47 UTC
Visiting link for latest release: https://github.com/bitcoin-wallet/bitcoin-wallet/releases/latest
will redirect to https://github.com/bitcoin-wallet/bitcoin-wallet/releases/tag/v5.45
which is old version 5.45 from 2018 that also shown in releases on homepage at:
https://github.com/bitcoin-wallet/bitcoin-wallet/

Use github releases for new versions and add universal .apk file as asset to github release including a description with changelog content.

**Comment by schildbach** [comment] 2021-06-04 13:23
I few days ago, I removed all the old releases from GitHub, and the references to binaries at stores. My thinking is that if you're on GitHub you're a developer and should build the binaries yourself.

I think this issue is now more or less a duplicate of #620.

**Comment by emanuelb** [comment] 2021-06-04 13:50
Yes, it's kinda duplicate, github releases is useful cause they include changelog of the release & source & apk download, also github is site that is rarely blocked (google-play is blocked in china, while github isn't) also it's allow unauthenticated downloaded (no need to login to github to download) which is probably required for `Binaries` fdroid directive for reproducible-builds checking and using upstream signature.
it's possible to upload apk elsewhere like website, I think github releases are better.
There are visitors of github who aren't developers, also even developers don't mean they want to build the app or able to (as they non mobile developers, no java build systems experience, etc...) last time I tried to build this app it fails with FTBFS cause it's used probably newer gradle version installed: #696 which has open PR that probably fix it.

**Comment by Bushmaster39** [comment] 2021-07-02 19:43
Nice budge

**Comment by schildbach** [comment] 2021-07-11 17:54
@emanuelb The F-Droid build luckily doesn't depend on the presence of a binary on external servers. Rather, the developer signaure is included with the metadata.

**Comment by schildbach** [comment] 2021-07-11 17:55
Atm I do not intend to publish binaries on GitHub. They can be downloaded from F-Droid easily. So I'll close this.

**Closed by schildbach** 2021-07-11 17:55 UTC
