### ISSUE TITLE
"Raise network fee" too aggressive

### ISSUE THREAD

**Issue by codewiz** [bitcoin-wallet/bitcoin-wallet#464] opened 2017-10-28 02:38 UTC
Yesterday I sent a transaction with "Economic" fee. The transaction was 226 bytes and Bitcoin Wallet computed a fee of 0.05 mBTC, about $0.30, or 22 satoshi/byte. According to https://bitcoinfees.21.co/, this fee is way too low. Anything below 100 sat/byte might take days to go through, or never clear at all.

So today I tried bumping the fee with the "Raise network fee" function, but this time the computed value is way too high: 0.94 mBTC, or 415 satoshi/byte. This is equivalent to $5.64.

I think there are two separate fee estimation bugs here, but I wouldn't mind the Economic fee being too aggressively economic if I could bump the fee a bit at a time until the transaction finally clears.

**Comment by codewiz** [comment] 2017-10-28 02:49
Random thought: it looks like we'll have to live with high Bitcoin transaction fees for some time. Fee estimation can no longer be an internal detail that users don't need to know or care about.

How about this: if a transaction has not cleared for more than 1h, the app pops an Android notification offering to bump the fee a bit (or perhaps offer 2-3 different options). It's quite annoying, but not as annoying than discovering that an important transaction never cleared after several days.

**Comment by schildbach** [comment] 2017-10-31 15:07
On Oct 27, economic transactions were delayed for 2 days. That's well in the description/purpose of that fee level, which says you don't care about confirmation times.

Raising the fee needs to pay not only for the payment to raise, but also for the 'raise fee' transaction itself. This is why it appears to be so high, but if you consider both transaction it was much lower (probably around 230 sat/b).

**Comment by AlldayBoutique** [comment] 2017-11-03 11:20
Im still waiting for transactions yo show at least 6 transactions that has now showed in my accpunt that's Not computed but says completed but its not in other accoun

**Comment by codewiz** [comment] 2017-11-03 20:06
> Raising the fee needs to pay not only for the payment to raise, but also for the 'raise fee' transaction
> itself. This is why it appears to be so high, but if you consider both transaction it was much lower
> (probably around 230 sat/b).

Then I don't understand how raising transaction fees actually works. I thought Bitcoin Wallet worked just like the Satoshi client, which broadcasts a new transaction spending the same inputs, with a higher sequence number and higher fee (perhaps sometimes you need an additional input to cover the higher fee).

**Comment by schildbach** [comment] 2017-11-03 20:29
It doesn't work like that. Rather you broadcast a new payment to yourself, spending one of the outputs of the transaction to raise the fee of. It's called CPFP (child-pays-for-parent).

**Comment by codewiz** [comment] 2017-11-14 19:06
Are there any plans to support replace-by-fee? It seems it would lead to lower overall fees and less wasted block space.

**Comment by schildbach** [comment] 2017-11-14 20:15
RBF is a broken concept. It breaks the transaction graph (causing dead transactions) and only the sender can use it (while raising fee is usually needed on the receiving side). So no, except maybe in special usecases.

**Comment by mjamin** [comment] 2017-12-29 10:49
Let's say I want to move all funds from Wallet A (this software) into a new and empty Wallet B.

What are my options when the fee I used was too low and the transaction won't confirm. Is there a time out after which I can try again? Do I need to move more funds to Wallet A in order to make a CPFP transaction?

**Comment by codewiz** [comment] 2017-12-29 11:16
@schildbach wrote:

> RBF is a broken concept. It breaks the transaction graph (causing dead transactions) and only the
> sender can use it (while raising fee is usually needed on the receiving side).
> So no, except maybe in special usecases.

Can you at least allow transactions to be marked as replaceable, so a user can still get them unstuck by generating a RBF transaction using the Satoshi client (after importing the wallet's private key, obviously).

**Comment by codewiz** [comment] 2017-12-29 11:28
@mjamin wrote:

> Let's say I want to move all funds from Wallet A (this software) into a new and empty Wallet B.
>
> What are my options when the fee I used was too low and the transaction won't confirm?
> Is there a time out after which I can try again? Do I need to move more funds to Wallet B
> in order to make a CPFP transaction there?

The easy way: send some more funds to the wallet, then raise the fee :-)

The hard way:

1. Export the wallet and transfer it to a computer (taking precautions to ensure you don't expose the key)
2. Import the wallet into a client supporting low-level wallet manipulation, such as Satoshi or Electrum
3. Follow one of the many guides to create a double-spend transaction
4. Relay the new transaction until it's mined by someone (there are public gateways that accept double-spends)

Note that while a double-spend isn't an _illicit_ transaction, wallet software makes it hard to create and relay them because, well, it could be used for fraud. Whichever transaction is included in a block will become the _real_ one, at which point the others will become invalid and get dropped from the mempool.

**Comment by schildbach** [comment] 2017-12-31 14:56
@codewiz "Marking as replaceable" is exactly RBF.

**Comment by schildbach** [comment] 2018-03-25 06:12
Closing this, as fees have come down to a sane level.

**Closed by schildbach** 2018-03-25 06:12 UTC

**Comment by My1** [comment] 2021-01-20 18:16
> @codewiz "Marking as replaceable" is exactly RBF.

I would say not exactly, as RBF is 2 things.

1) marking your transaction to be replaced later (something many wallets do)
2) doing the actual replacement.

and I think with fees not really being low overly recently I think it would be sensible to at least give the flag out for RBFing later.

**Comment by tyrion** [comment] 2021-02-09 16:16
This problem is not solved at all for me.
I am not sure if it is because my wallet is very old. Anyway I am using the last version of bitcoin-wallet downloaded from the Play Store.

The economic fee is way too low (~0.20 EUR) and raising the fee is insanely high (0.000597 BTC, around 20 EUR at the moment).

It would be nice if there was a way to set a custom fee. Otherwise, the app, which is very nice, becomes unusable, at least for me :(

**Comment by schildbach** [comment] 2021-02-09 17:23
Raising the fee assumes that for the user the transaction has changed to "priority". That's why the fee is so high – yes, currently it's insane to send transactions with priority fee.

**Comment by My1** [comment] 2021-02-09 17:53
and also the part that CPFP is more expensive in general

**Comment by tyrion** [comment] 2021-02-09 18:07
Thanks for the quick reply. So, I guess I have no other choice than to wait.
What happens if I try to do another transaction, while the previous is still unconfirmed? Is it safe? or I have no choice other than not to use the wallet for weeks?

As a workaround for future transactions is it possible to manually edit the fees of the app, by messing up with the data files, *without having root access*?

**Comment by My1** [comment] 2021-02-09 18:25
well in theory if the other transaction is high enough it could drive up the average sat per vbyte and if you use enough that would be CPFP in a more practical sense.
also since the transaction can't be RBF'd it's likely semi-safe to use even if it wont confirm for a while.

I am honestly curious tho how many sat/vB the current fee levels are.

**Comment by tyrion** [comment] 2021-02-09 18:40
> well in theory if the other transaction is high enough it could drive up the average sat per vbyte and if you use enough that would be CPFP in a more practical sense.

Just to be sure I understood. Here with "high enough" you mean the fee is high enough, not the amount of the transaction, right?

> also since the transaction can't be RBF'd it's likely semi-safe to use even if it wont confirm for a while.

The *semi* part in semi-safe is worrying me a bit :rofl: . Could you please clarify?

> I am honestly curious tho how many sat/vB the current fee levels are.

Using the economic fee, for my transaction it was 2.5 satoshi per vbyte. It's taking days already, and I wonder if it can get stuck forever?

**Comment by My1** [comment] 2021-02-09 18:52
yes I mean the fee.

well I dont know if transactions get thrown out of the mempool someday or whatever but as this wallet doesnt set the RFP flag the transaction cant just easily get replaced.

2,5 sat/vb, lol that's a joke according to the current feescape, is this app using hard coded values?

there is a chance that it could get stuck forever if there will be enough transaction to keep the mempool filled, but maybe there might also be an avalanche of blocks coming in fast to bring the pool to a more bearable level

**Comment by schildbach** [comment] 2021-02-09 18:54
> > I am honestly curious tho how many sat/vB the current fee levels are.
> 
> Using the economic fee, for my transaction it was 2.5 satoshi per vbyte. It's taking days already, and I wonder if it can get stuck forever?

It won't be forever, but it can take weeks. I think the longest we have been waiting at the 2017 bubble was 3 months.

Fee is curently at about 140 sat/byte.

**Comment by schildbach** [comment] 2021-02-09 19:01
> As a workaround for future transactions is it possible to manually edit the fees of the app, by messing up with the data files, _without having root access_?

Currently there is no way to set an arbitrary fee, other than modifying the source code.

I wonder what fee would you have picked? What's your usecase? The app comes with three sensible presets.

**Comment by My1** [comment] 2021-02-09 19:07
no idea what the "sensible" presents are but I would usually choose the fees based on the current fee space as one can see on many places e.g. mempool.space

**Comment by schildbach** [comment] 2021-02-09 19:20
The presets cover these usecases:

- Priority: Send as fast as possible, at all cost. Otherwise I'm going to miss an opportunity.
- Economic: Send as cheap as possible. Time is not important. I'm sending to my own wallet, or to a friend who trust me anyway.
- Normal: Try to find a good balance between Cost and Time. I'm sending a payment that is not super important, just a normal payment. This is the default.

The "power user use-case" (use external tools to calculate your own fee) is not supported because the app aims at simple usage and non-technical users. It's _not_ a power tool.

**Comment by My1** [comment] 2021-02-09 19:23
but many wallets nowadays even on a similar system at least do their fees based on the current feescape, instead of throwing 2,5 sat which is basically nothing and could really take forever.

**Comment by schildbach** [comment] 2021-02-09 19:28
So again, what fee would you have picked? What is your usecase?

**Comment by My1** [comment] 2021-02-09 19:33
well my usecase would be being REASONABLY fast while not crazily overpaying

also depending on how the chain goes even the current priority might not be enough, according to mempool.space that is medium now.

**Comment by schildbach** [comment] 2021-02-09 19:35
> well my usecase would be being REASONABLY fast while not crazily overpaying

That's "normal". You don't have to do anything regarding fee.

**Comment by My1** [comment] 2021-02-09 19:59
that would depend a lot on the current feescape. if the blockchain is effectively empty normal could be crazy overpaying (I dunno its value) when you can easily push through with sats in the low single digits.

**Comment by schildbach** [comment] 2021-02-09 20:07
The presets are meant to abstract from that. Of course, if blocks are empty fees go down accordingly, just like they have climbed to the current high in the past weeks. As a user, for normal transactions just use "normal" fee.

**Comment by My1** [comment] 2021-02-09 20:26
well yes sure but maybe this would generally go better if the presets would automatically adjust to current levels.

like the 2 sat/vb area according to mempool hasnt been touched for basically a month now*, this is beyond eco

like i would expect eco to be a day or 2, normal to be one to a few hours and prio as in "try to get in next block", and prio being 140, that wouldnt have worked likely as from the last 8 blocks 4 have had a spread starting at over 140.

hardcoded values are not too awesome if you can get numbers dynamically. iirc the hardware wallet's companion wallets should all have dynamic fees for btc as the feescape is way too wild.

*except for a very small place where the graph on mempool.space drops to zero which i think to be a glitch

**Comment by tyrion** [comment] 2021-02-09 21:17
> > well my usecase would be being REASONABLY fast while not crazily overpaying
> 
> That's "normal". You don't have to do anything regarding fee.

The point is that the economic fee is really too low, at least at this moment. I am willing to wait *days*, not weeks or months. The normal fee is also higher than necessary. The priority fee is insanely high.

The right thing to do seems to be to dynamically adjust the fees. If that is too much work, why not allow the possibility to choose a custom fee? In my case I would have selected something in between the economic fee (~0.20 EUR) and the normal one (~10.8 EUR). The gap seems huge to me.

Looking here ( https://bitcoinfees.earn.com/ ), it seems to me that the low fee is in the first row (taking forever) and the normal fee is the last row (very fast). Again, a lot of middle options.

Anyway, I understand that you might not have the time, or may not find these issues relevant enough, and that is OK. I just hope at least it is clear to you why many users believe this is not optimal behaviour.

Finally, @schildbach, I would be very grateful if you could help me figure out what I can do now, if waiting a month is not an option. *Assuming I do not care about the transaction I made* with the low fee, can I make a new one with a higher fee, or am I supposed to wait first that the other one completes?

Thank you again :)

**Comment by My1** [comment] 2021-02-09 21:23
I aint even sure if earn is up to date as mempool.space has realtime mempool data in it and well I would say that saying 101 cuts next block is very advantageous.

**Comment by schildbach** [comment] 2021-02-09 21:48
Economic fee is meant to be low, because it's meant for when time is not important. Priority fee is "insanely high" because the Bitcoin network is overloaded since weeks without interruption. Nothing this app can do about. Anything inbetween is extremely difficult to predict. For example, at the current network load even a 80 sat/b fee can very well lead to weeks of waiting time.

For support on a specific payment, please tap on the transaction and pick "report issue" from the transaction's context menu.

**Comment by My1** [comment] 2021-02-09 22:36
the issue is tho that this is all a very relative term, like time is not important" is in my opinion not something I would say to a payment that takes over a month.
sure you cant predict everything but one could possibly also add an extra point in the settings menu to enable custom fees as a semi-hidden option (something I have seen other wallets do) and be a bit more dynamic.

I mean 140 on prio is starting to not be enough anymore. and having to change code and get the update on play takes way too long to issue changes.

**Comment by tyrion** [comment] 2021-02-10 11:31
I understand that the developers do not want to complicate the tool, and said that bitcoin-wallet aims "at simple usage and non-technical users". Seeing there a number of non-technical users (including myself, since I do not know much about bitcoins) having problems with fees, I believe some kind of improvement might be welcome by your users.

Considering your constraints, my suggestion would be to either (A) remove the economic and priority fees altogether and just offer a normal fee that is more or less guaranteed to confirm in some hours (max 24), or (B) at least improve the message the users get when selecting the economic fee including a warning that the transaction might be stuck forever if the fee is too low.

I argue that using the economic fee of bitcoin-wallet is not for "non-technical users", but requires an understanding of how the bitcoin transactions work, which non-technical users probably do not have. Therefore, at least in my case, being warned about the potential *unlimited* waiting time, would have helped.

I'll gladly send you a donation, with the economic fee, when this gets "fixed" :smile:
Jokes aside, thank you again for bitcoin-wallet.

**Comment by o5786486** [comment] 2021-02-21 01:17
@schildbach 
If I use the empty wallet in the transaction, can I still use the raise network fee option? My wallet is currently empty and I can’t find an option raise network fee option in the transaction's context menu Will this option appear if I deposit money in my wallet?

**Comment by schildbach** [comment] 2021-02-21 09:28
In this case you can't, as no output goes back to you which you could build a CPFP transaction on.

But the recipient can raise the fee.
