### ISSUE TITLE
Sync is stuck

### ISSUE THREAD

**Issue by DTUBBS08** [bitcoin-wallet/bitcoin-wallet#1153] opened 2024-06-23 20:18 UTC
Sync is stuck at 849198. Sync is 14 hours behind.

**Comment by 32xxl** [comment] 2024-06-23 22:24
Have you fixed already? 
If no, don't panik, today is sunday. 
I have the same issue. 
Just make copy of private keys, and wait for updates from devs.

**Comment by DTUBBS08** [comment] 2024-06-23 22:38
Thank you, 32xxl

**Comment by DTUBBS08** [comment] 2024-06-23 22:42
My apologies, no it's not fixed yet

**Comment by schildbach** [comment] 2024-06-24 23:55
Duplicate of #1154.

**Closed by schildbach** 2024-06-24 23:55 UTC

**Comment by Laye27** [comment] 2024-07-07 03:57
Thanks
